### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#1]
Add a pull request template to the project.

**Comment by Halix267** [comment]
I want to work on this request @adityabisoi .Can u assign it to me

**Comment by adityabisoi** [comment]
@Halix267 You can work on one issue at a time.

**Comment by subhangi2731** [comment]
I am really interested and want to work on this request template. Can you please assign this to me @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 I have assigned you the issue. You can start working and make a PR on December 1.

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by adityabisoi** [comment]
@Pranav016 this issue has been assigned already.
