### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#10]
Add and implement tests for all new features introduced.

**Comment by subhangi2731** [comment]
can you please assign it to me? @adityabisoi

**Comment by adityabisoi** [comment]
One issue at a time, @subhangi2731

**Comment by adityabisoi** [comment]
@subhangi2731 Go ahead :)

**Comment by adityabisoi** [comment]
This issue requires UI modification first. To be assigned after #5 and #8

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @adityabisoi I want to work on this

**Comment by adityabisoi** [comment]
Again, go ahead:)

**Comment by adityabisoi** [comment]
@subhangi2731 Update tests ASAP.

**Comment by adityabisoi** [comment]
@subhangi2731 Just try to make the tests passing. That will be enough for now. We can add tests for each component once the project develops.
