### ISSUE TITLE
Add a styling guide

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#11]
Add a styling guide, such as `Airbnb` or `Google` style guide for react for a consistent styling.

**Comment by Curnow93** [comment]
I'll work on it

**Comment by adityabisoi** [comment]
@Curnow93 Actually, this project is to be a part of an open-source event (https://njackwinterofcode.github.io/). You can take part in the event if you want. However, if you really want to work on this now, go ahead :)

**Comment by adityabisoi** [comment]
@Curnow93 Are you working on this?

**Comment by Curnow93** [comment]
> @Curnow93 Are you working on this?

This is my first time using github, I'm unsure how to start.

**Comment by adityabisoi** [comment]
Maybe you can watch a couple of videos on contributing to GitHub.

**Comment by subhangi2731** [comment]
can you please assign it to me? @adityabisoi

**Comment by adityabisoi** [comment]
@Curnow93 Are you working on the issue? If you have any questions, use the Gitter channel in [README](https://github.com/adityabisoi/github-rest-api-v3/blob/main/README.md) to talk to developers. I am going to assign the issue to other members of the community.

**Comment by subhangi2731** [comment]
I want to work on this. Please assign this issue to me? @adityabisoi
