### ISSUE TITLE
Add Pagination Support

### ISSUE THREAD

**Issue by paramsiddharth** [adityabisoi/github-rest-api-v3#18]
The GitHub API calls don't always return complete data. Whether it is the `repos`, `gists`, `followers`, `following`, or `starred` endpoint, by default, the API responds with an array of 30 entries as the data, which we can extend upto 100 with the `?per_page=100` parameter in our GET requests. However, we will still receive only the last 100 entries until we manually navigate through the pages and collect entries. 

``` md
https://api.github.com/users/paramsiddharth/repos?per_page=100&page=3
```

To achieve that, we would need to manually navigate to the next page i. e. `?per_page=100&page=<next>` until the response data array is empty. Once the UI and visualizations are implemented, the fetching of further pages may optionally be bound to how far the user scrolls.

If approved, I would like to work on the issue.

**Comment by adityabisoi** [comment]
@paramsiddharth The pagination can be implemented after we clear the UI of the app. I'll assign it to you then.

**Comment by paramsiddharth** [comment]
Now that the concerns have been separated, all the business logic goes into `services/GitHub.js`. May I work on the issue? It won't hold back other PRs as there wouldn't be conflicts.

What I'll attempt to do is get the service to continue fetching and return an object with complete data.

**Comment by adityabisoi** [comment]
@paramsiddharth Go ahead
