### ISSUE TITLE
Add issue template: feature request

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#2]
Add an issue template for requesting new features in the project.

**Comment by Vrindagupta6828** [comment]
@adityabisoi  please assign me this

**Comment by adityabisoi** [comment]
@Vrindagupta6828 You can work on one issue at a time.

**Comment by Abjcodes** [comment]
Hey @adityabisoi, Can I work on this?

**Comment by adityabisoi** [comment]
@Abjcodes Go ahead.

**Comment by Abjcodes** [comment]
@adityabisoi Please review the PR and notify me if there are any changes to be made.
