### ISSUE TITLE
Change page title and icon

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#20]
Currently, the page title and icon are set to React default.

![Screenshot from 2020-12-02 11-39-50](https://user-images.githubusercontent.com/42573842/100835214-46f17c00-3493-11eb-8ee9-cd59cfbd4791.png)

 Change the title to the project name, and the icon to the GitHub logo.

**Comment by prabhat04011998** [comment]
Okay you can assign this to me.! @adityabisoi 
Provide the icon also.
