### ISSUE TITLE
Loaders to all the api calls

### ISSUE THREAD

**Issue by prabhat04011998** [adityabisoi/github-rest-api-v3#31]
Need to add loader to all the api calls, on both the routes.
While triggers the api call to fetch the data , then it takes some time, meanwhile it looks idle.so need to fill that gap with loader.

**Comment by prabhat04011998** [comment]
@adityabisoi  please add all the necessary labels and you can assign this to me.

**Comment by adityabisoi** [comment]
@prabhat04011998 Do you mean, a loading animation?

**Comment by prabhat04011998** [comment]
Yes A loading Animation

**Comment by adityabisoi** [comment]
@prabhat04011998 Go ahead

**Comment by adityabisoi** [comment]
@prabhat04011998 You working on this?

**Comment by prabhat04011998** [comment]
Yes i am working over it.
