### ISSUE TITLE
Adding an issue template

### ISSUE THREAD

**Issue by KerinPithawala** [adityabisoi/github-rest-api-v3#32]
Can I Make and configureStandardize the information you'd like contributors to include when they open issues in your repository?
I will provide an important checklist.

**Comment by adityabisoi** [comment]
@Kerveyfelix Issue templates are already added. However, you can add the checklist you are talking about. Just edit existing templates and make a PR.

**Comment by KerinPithawala** [comment]
Yes. I will follow this guideline.

**Comment by KerinPithawala** [comment]
Could you please add this issue as part of NWoC?
