### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#39]
Display error message when the wrong username is entered.

**Comment by tejaswinni51** [comment]
can i work on this @adityabisoi

**Comment by SedaII** [comment]
Hi! Did forked the project and discovered a bit the architecture of the project. I was thinking about making 2 kinds of jumbotron on Visualization.js, one for home and one for wrong username entering. Or maybe I can use an id and use some js to handle h1 and p content. Or should I think about making a component for the jumbotron ?

Or I can simply use window.alert() but I was thinking about something prettier than alert box.

**Comment by adityabisoi** [comment]
No alerts, a simple message in red saying `Username doesn't exist`.

**Comment by adityabisoi** [comment]
@tejaswini22199 Are you working on the issue?

**Comment by tejaswinni51** [comment]
@adityabisoi  I have become busy with my exams I'll try to do it by tonight

**Comment by tejaswinni51** [comment]
@adityabisoi  could you please review my PR on this issue
