### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#4]
Add CONTRIBUTING.md to the project.

**Comment by yashgautam9274** [comment]
Assign me  for this issue

**Comment by adityabisoi** [comment]
You will be assigned on December 1 after the beginning of the event.

**Comment by yashgautam9274** [comment]
Thank You

**Comment by adityabisoi** [comment]
@yashgautam9274 I have assigned you the issue. You can start working on it but make a PR on December 1.

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by adityabisoi** [comment]
@Pranav016 This issue has already been assigned to someone else. Try an issue that has not been assigned yet.
