### ISSUE TITLE
Hosting of the Complete Repo

### ISSUE THREAD

**Issue by Tejas1510** [adityabisoi/github-rest-api-v3#40]
The project is not hosted anywhere
So when someone wants to see if what the project is about they have to download the complete project and run it which become tedious
So hosting would simply it 
I would host it on Netlify
Can I go for it @adityabisoi

**Comment by adityabisoi** [comment]
The project is hosted at https://adityabisoi.github.io/github-rest-api-v3/

**Comment by adityabisoi** [comment]
It's in the README. Closing the issue. Thanks, though!

**Comment by Tejas1510** [comment]
oh Sorry I totally miss that
Just a small suggestion add the link in the Project Description so it will be easy to acces

**Comment by adityabisoi** [comment]
Do you wanna do it? That counts as a contribution too. Please doo if you want

**Comment by Tejas1510** [comment]
Sure will do it @adityabisoi
