### ISSUE TITLE
Feature: Update the compare table with the difference status 

### ISSUE THREAD

**Issue by prabhat04011998** [adityabisoi/github-rest-api-v3#42]
In compare user feature add another column to show which user have more no of feature.
 
use green and red color for showing difference.

![image](https://user-images.githubusercontent.com/28345582/101906252-ac094800-3bde-11eb-80c8-8352b46b2bd1.png)

**Comment by prabhat04011998** [comment]
@adityabisoi  you can assign this to me!

**Comment by adityabisoi** [comment]
Instead of adding a different column, which as I see indicates the positives/negatives for the 1st user only, we can color the greater value in `Green` and the lower value as `Red` in the two columns.

**Comment by prabhat04011998** [comment]
okay i understand you point , 
but don't you think it'll reduce the UX, as need to check both the values while another column is directly showing the user1 over user2 ,on two basis,
1) First directly clear by color.(color is first impression)
2) By Sign (+ve ,-ve, either first is greater or smaller)

**Comment by adityabisoi** [comment]
What if the user enters his/her name in the second field instead of the first? The currently implemented feature is a `user-1` centred one. Do you have a fix for this?

**Comment by prabhat04011998** [comment]
yes but it's clear like first user is comparison with second , if user put in second then also it's explanatory .

but i can do any of the change either your approach or this one, whatever you'll approve.

**Comment by adityabisoi** [comment]
I was thinking of adding a positive/negative arrow and value beside the stats. Something like SENSEX

![Screenshot from 2020-12-13 09-55-03](https://user-images.githubusercontent.com/42573842/102003131-6dcc6f80-3d29-11eb-8129-aea8eed2d075.png)

If you can do that, tell me and I will assign this to you.

**Comment by prabhat04011998** [comment]
okay i'll do it , confirm me i have to make this for both the user,

like if one user is up by x then second will be low by x.

**Comment by adityabisoi** [comment]
Let's do only green ups and not downs

**Comment by prabhat04011998** [comment]
![image](https://user-images.githubusercontent.com/28345582/102095137-2b9a4f80-3e49-11eb-9e14-6871584c106e.png)

you were talking about something like that @adityabisoi confirm and assign this to me.

**Comment by adityabisoi** [comment]
Yes, go ahead. Try adding small green uphead arrow, that would look better:)
