### ISSUE TITLE
Invalid username alert keeps poping at each input

### ISSUE THREAD

**Issue by SedaII** [adityabisoi/github-rest-api-v3#46]
After one invalid username, alert box keeps poping
I think that data is still undefined and Vizualisation is refreshing at each event or input.
I think we should check if username is valid at each form submitting (sendUsername fn)

**Comment by adityabisoi** [comment]
@SedaII Please go ahead

**Comment by SedaII** [comment]
Thanks, I'll work on it tomorrow!

**Comment by adityabisoi** [comment]
@SedaII Please make a PR on this by tonight.
