### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#5]
Add better UI to the project, probably use a ReactJS framework such as Ant Design or Material UI

**Comment by paramsiddharth** [comment]
I would like to work on this.

**Comment by adityabisoi** [comment]
@paramsiddharth Go ahead.

**Comment by paramsiddharth** [comment]
Should I implement the UI taking expecting the availability of multiple endpoints? PR #15 would need to be merged into `adityabisoi:main` before I do that. Please review it and let me know.

**Comment by adityabisoi** [comment]
Just enhance the UI by adding a navbar, header, and other stuff. Visualizing the data from endpoints is a part of issue #8

**Comment by paramsiddharth** [comment]
Noted! I'll continue with designing the UI.
