### ISSUE TITLE
The profile endpoint has been forgotten in the Github.js from 'Recover lost pagination update'

### ISSUE THREAD

**Issue by SedaII** [adityabisoi/github-rest-api-v3#52]
Visualization.js is still working with the profile endpoint(which is missing in Github.js), so the app stop working when Visualization try to build with props.data.profile

**Comment by adityabisoi** [comment]
@SedaII Resolve this issue if you can.

**Comment by paramsiddharth** [comment]
The fix to this issue requires the following changes:
- Add the '/' endpoint to the array of endpoints.
- Handle the case of '/' separately within `getEndpoint`.
- Before `getDetails` returns the final promise, rename the '/' key to 'profile'.

That will solve the problem. @SedaII Let me know on Gitter if you face any issues.
