### ISSUE TITLE
Beautify and enhance README

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#53]
Make the `README.md` (very) pretty.

* Add cool badges.
* Add a `Table of contents` section similar to the screenshot (with pointers to contents in this README)
![Screenshot from 2020-12-23 22-30-10](https://user-images.githubusercontent.com/42573842/103020948-6306ab80-456f-11eb-837b-0b04d4b45592.png)

**Comment by adysis14** [comment]
hello ! @adityabisoi sir, I'm interested to solve this issue.

**Comment by adysis14** [comment]
can you just give me a brief info. about what to write under these sub -headings?

**Comment by adityabisoi** [comment]
@adysis14 I am assigning you the issue. The links In `Table of Contents` must point to the corresponding headers in the README.

**Comment by adityabisoi** [comment]
@adysis14 Are you working on this or not?

**Comment by adysis14** [comment]
@adityabisoi  can you please review my pull request!
