### ISSUE TITLE
Add GitHub Star and Fork buttons

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#6]
Add a `Star` and `Fork` button to the homepage

**Comment by Vrindagupta6828** [comment]
@adityabisoi Please assign this to me.

**Comment by adityabisoi** [comment]
@Vrindagupta6828 I have assigned you the issue. You can start working on it but make a PR on December 1.

**Comment by Vrindagupta6828** [comment]
@adityabisoi Please can you brief a little how to do it?

**Comment by adityabisoi** [comment]
Head over to the Gitter channel for discussions.

![Screenshot from 2020-11-30 21-04-29](https://user-images.githubusercontent.com/42573842/100629778-b2323580-334f-11eb-9d60-16242e9809bb.png)

Add buttons like these to a new header. Search on the internet for GitHub buttons.

**Comment by adityabisoi** [comment]
@Vrindagupta6828 are you working on this issue?

**Comment by Vrindagupta6828** [comment]
@adityabisoi yes

**Comment by yashgautam9274** [comment]
I want to work on this issue
Can you explain more

**Comment by adityabisoi** [comment]
@Vrindagupta6828 What's your progress? Its already been 3 days.

**Comment by yashgautam9274** [comment]
@adityabisoi  i want to work on this issue

**Comment by Vrindagupta6828** [comment]
@adityabisoi I am working on it..just give me a day or two.

**Comment by adityabisoi** [comment]
@Vrindagupta6828 Make a PR before 7 December.

**Comment by Vrindagupta6828** [comment]
@adityabisoi sure

**Comment by adityabisoi** [comment]
@Vrindagupta6828 Unassigning you the issue. Please take up an issue you think you can resolve.

**Comment by subhangi2731** [comment]
I can do this. Can you please assign me @adityabisoi

**Comment by subhangi2731** [comment]
And the tests which i have added i have updated that

**Comment by shrey27tri01** [comment]
@subhangi2731 Are you working on this issue? 
If not, can I take up this issue @adityabisoi?

**Comment by subhangi2731** [comment]
@shrey27tri01 I am working on this issue currently 
@adityabisoi I will make a pr by today

**Comment by adityabisoi** [comment]
@subhangi2731 Make a PR by 12 December, otherwise you will be unassigned.

**Comment by subhangi2731** [comment]
I am working on it will surely do the pr dont worry

**Comment by tejaswinni51** [comment]
hey @adityabisoi  what is this issue could you please describe will they denote number stars and forks of this repo

**Comment by adityabisoi** [comment]
Yes, they will

**Comment by tejaswinni51** [comment]
if possible and no one is working could you please assign this issue to me. @adityabisoi

**Comment by akshay1027** [comment]
can you assign this task to me if nobody is working on this @adityabisoi
