### ISSUE TITLE
Create a dev branch where we will use API token for test/dev purposes

### ISSUE THREAD

**Issue by SedaII** [adityabisoi/github-rest-api-v3#63]
I want to implement a feature to use if wanted our personal github token to reach rate limit to 5k per hour. However, I was thinking that we won't need those feature in main branch, so I thought about a dev branch(since it's for dev or test purposes). Or maybe there's another way.

**Comment by adityabisoi** [comment]
Can you elaborate on this a bit?

**Comment by SedaII** [comment]
@adityabisoi Heres detail, I'm sorry I didn't explain much.

**Comment by adityabisoi** [comment]
@SedaII Indeed, using a personal Token comes with a lot of feature additions and not only increasing the rate limit. I am creating a `dev` branch. I would merge it into `main` once some useful improvements are made.
