### ISSUE TITLE
Visualize data on homepage

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#8]
Visualize the data accessed on the homepage. Currently, the data is logged on the console.

**Comment by paramsiddharth** [comment]
I would like to work on this! Could you assign it to me?

**Comment by adityabisoi** [comment]
@paramsiddharth One issue at a time, mate!

**Comment by prabhat04011998** [comment]
Hey i can work on this please assign,
i was just wondering even data is not visible , but now i got it in console.

**Comment by adityabisoi** [comment]
@prabhat04011998 This issue should be resolved after issue #5.  You have to work on the UI to display the data on the webpage.

**Comment by prabhat04011998** [comment]
this is the issue #8 , i have to design the UI for data visualization right?

**Comment by paramsiddharth** [comment]
> this is the issue #8 , i have to design the UI for data visualization right?

@prabhat04011998 I think he meant #5 . You need to work on the UI to implement the visualization, and I am working on just that. :)

**Comment by prabhat04011998** [comment]
@paramsiddharth  @adityabisoi  any issue on which i can work available?
i think everything is dependent on these starting issue.
getting data ,showing data ,then we can think of something.

**Comment by paramsiddharth** [comment]
> @paramsiddharth @adityabisoi any issue on which i can work available?
> i think everything is dependent on these starting issue.
> getting data ,showing data ,then we can think of something.

@prabhat04011998 I think you work on issues #1, #2, #3, #4, or #10, as they are not dependent on the UI at the moment. #10 might require the UI to be finalized, though!

**Comment by prabhat04011998** [comment]
everything is already assigned.!

**Comment by adityabisoi** [comment]
@prabhat04011998 check #11 and #20

**Comment by prabhat04011998** [comment]
Hey @adityabisoi  , 
I think now i can take this issue?
If yes , please assign it to me.

**Comment by adityabisoi** [comment]
@prabhat04011998 Go ahead.

**Comment by prabhat04011998** [comment]
I have to show the data on homepage , which is raw right now?

**Comment by adityabisoi** [comment]
@prabhat04011998 yes.

**Comment by prabhat04011998** [comment]
/compare
![image](https://user-images.githubusercontent.com/28345582/101260502-86032400-3756-11eb-9326-c940493a248d.png)
Please Check !
@adityabisoi

**Comment by adityabisoi** [comment]
@prabhat04011998 Share your designs in the Gitter page. Issues section is not for discussions.
