### ISSUE TITLE
Add section for comparing two users

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/github-rest-api-v3#9]
Add a section for entering two usernames and comparing fetched metrics such as followers, repository count, and stars.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @adityabisoi

**Comment by adityabisoi** [comment]
One issue at a time, @subhangi2731

**Comment by prabhat04011998** [comment]
@adityabisoi  can you assign this to me?

**Comment by adityabisoi** [comment]
@prabhat04011998 Go ahead
